name: Trigger auto deployment for ca-nex-mcphub-01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-nex-mcphub-01-AutoDeployTrigger-1838fe26-dc85-4e13-835d-b6e37a2c8ccd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CANEXMCPHUB01_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CANEXMCPHUB01_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CANEXMCPHUB01_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}apps/api
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: nexianmcphub01.azurecr.io
          registryUsername: ${{ secrets.CANEXMCPHUB01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CANEXMCPHUB01_REGISTRY_PASSWORD }}
          containerAppName: ca-nex-mcphub-01
          resourceGroup: rg-nex-test-play-uks-001
          imageToBuild: nexianmcphub01.azurecr.io/ca-nex-mcphub-01:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


